renderer.setSize(sizes.width, sizes.height);
renderer.setClearColor("#00ff00", 1);
renderer.setPixelRatio(Math.min(window.devicePixelRatio, 2));
renderer.physicallyCorrectligths = true;
renderer.outputEncoding = THREE.sRGBEncoding;
renderer.toneMapping = THREE.ACESFilmicToneMapping;

const animate = () => {
  controls.update();

  renderer.renderAnimationFrame(animate);
};
animate();
